image: Visual Studio 2017

configuration:
  - Debug
  - Relase 
  
clone_folder: c:\projects\sc

platform:
- x86
- x64

install:
  - cd c:\projects\sc
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017" ..

build_script:
  - cmake -DBUILD_SHARED_LIBS=ON .
  - cmake --build .
  - cmake -DBUILD_SHARED_LIBS=OFF .
  - cmake --build .
  
deploy:
    provider: GitHub
    artifact: /.*\.lib/    
    draft: false
    prerelease: false
    auth_token:
    secure: WCGi6SXwa6VaPyLH6fZCrmTix+e2FA3zwzhNg8dSf3EdrcecGIR3Z0qG/vssOdfA
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: true       # deploy on tag push only
