image: Visual Studio 2017

configuration:
  - Relase 
  
clone_folder: c:\projects\sc

platform:
- x64

skip_non_tags: true

install:
  - cd c:\projects\sc
  - mkdir build
  - cd build

build_script:
  - npm install -g @angular/cli
  

      
