image: Visual Studio 2017

configuration:
  - Debug
  - Relase 
  
clone_folder: c:\projects\sc

platform:
- x86
- x64

skip_non_tags: true

install:
  - cd c:\projects\sc
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017" ..

build_script:
  - cmake -DBUILD_SHARED_LIBS=ON .
  - cmake --build .
  - cmake -DBUILD_SHARED_LIBS=OFF .
  - cmake --build .
  
artifacts:
  - path: '**\*.lib'
    
deploy:
  provider: GitHub
  artifact: /.*\.lib/    
  draft: false
  prerelease: false
  auth_token:
    secure: WCGi6SXwa6VaPyLH6fZCrmTix+e2FA3zwzhNg8dSf3EdrcecGIR3Z0qG/vssOdfA
  on:
    appveyor_repo_tag: true       # deploy on tag push only

      